# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=255, verbose_name='信息来源')),
                ('name', models.CharField(max_length=255, verbose_name='职位名')),
                ('salary_from', models.IntegerField(default=0, verbose_name='工资低点')),
                ('salary_to', models.IntegerField(default=0, verbose_name='工资高点')),
                ('is_annual_salary', models.BooleanField(default=False, verbose_name='是否为年薪')),
                ('is_negotiable', models.BooleanField(default=False, verbose_name='是否面议')),
                ('years_of_work_from', models.IntegerField(default=0, verbose_name='工作年限低点')),
                ('years_of_work_to', models.IntegerField(default=50, verbose_name='工作年限高点')),
                ('work_place', models.CharField(max_length=255, verbose_name='工作地点')),
                ('degree', models.CharField(choices=[('1', '高中及以下'), ('2', '大专'), ('3', '普通本科'), ('4', '研究生'), ('5', '博士及以上'), ('6', '未知')], max_length=255, verbose_name='学历要求')),
                ('temptation', models.CharField(max_length=255, verbose_name='职位诱惑')),
                ('release', models.DateField(verbose_name='发布日期')),
                ('description', models.TextField(verbose_name='职位描述')),
                ('firm_introduction', models.TextField(verbose_name='公司简介')),
                ('firm_scale_from', models.IntegerField(default=0, verbose_name='公司规模低点')),
                ('firm_scale_to', models.IntegerField(default=100000, verbose_name='公司规模高点')),
                ('firm_nature', models.CharField(choices=[('1', '国企'), ('2', '外企'), ('3', '合资'), ('4', '民营'), ('5', '未知')], default='4', max_length=255, verbose_name='企业性质')),
                ('firm_industry', models.CharField(max_length=255, verbose_name='企业行业')),
                ('firm_location', models.CharField(max_length=255, verbose_name='公司地址')),
                ('firm_website', models.CharField(default='', max_length=255, verbose_name='公司网站')),
                ('is_alive', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
            ],
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
