# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20170803_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='url',
            field=models.URLField(default='', verbose_name='信息链接'),
        ),
    ]
