# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-04 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_recruit_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_introduction', models.TextField(verbose_name='公司简介')),
                ('firm_name', models.CharField(default='', max_length=255, verbose_name='公司名')),
                ('firm_scale_from', models.IntegerField(default=0, verbose_name='公司规模低点')),
                ('firm_scale_to', models.IntegerField(default=100000, verbose_name='公司规模高点')),
                ('firm_nature', models.CharField(choices=[('1', '国企'), ('2', '外企'), ('3', '合资'), ('4', '民营'), ('5', '其他'), ('6', '股份'), ('7', '上市')], default='4', max_length=255, verbose_name='企业性质')),
                ('firm_industry', models.CharField(max_length=255, verbose_name='企业行业')),
                ('firm_location', models.CharField(max_length=255, verbose_name='公司地址')),
                ('firm_website', models.CharField(default='', max_length=255, verbose_name='公司网站')),
                ('is_alive', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
            ],
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='firm_industry',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='firm_introduction',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='firm_location',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='firm_nature',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='firm_scale_from',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='firm_scale_to',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='firm_website',
        ),
        migrations.AddField(
            model_name='recruit',
            name='belong',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.Firm', verbose_name='所属公司'),
        ),
    ]
