# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-04 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20170804_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='member',
            field=models.IntegerField(default=0, verbose_name='招聘人数'),
        ),
    ]
