# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_recruit_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='firm_lat',
            field=models.FloatField(default=-1, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='firm',
            name='firm_lng',
            field=models.FloatField(default=-1, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='firm_nature',
            field=models.CharField(choices=[('1', '国企'), ('2', '外企'), ('3', '合资'), ('4', '民营'), ('5', '其他'), ('6', '股份'), ('7', '上市')], default='5', max_length=255, verbose_name='企业性质'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='member',
            field=models.IntegerField(default=-1, verbose_name='招聘人数'),
        ),
    ]
