# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20170812_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='is_add',
            field=models.BooleanField(default=False, verbose_name='是否添加'),
        ),
    ]
