# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20170812_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.TextField(verbose_name='薪水分析')),
                ('skill', models.TextField(verbose_name='技能树')),
                ('require', models.TextField(verbose_name='职位方向')),
                ('location', models.TextField(verbose_name='地理位置')),
                ('scale', models.TextField(verbose_name='公司规模')),
                ('degree', models.TextField(verbose_name='学历分布')),
            ],
        ),
    ]
