# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20170817_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapeddata',
            name='created_time',
            field=models.DateField(auto_now=True),
        ),
    ]
